var users = [
    {
        id: 1,
        username: 'johnjohn',
        email: 'johnn@example.com',
        age: 20,
        city: 'New York',
        phone: '123-456-7890',
        password: 'password',
        role: 'admin',
        about: 'I am a web developer',
    },
    {
        id: 2,
        username: 'array',
        email: 'abc',
        age: 20,
        city: 'New York',
        phone: '123-456-7890',
        password: 'abc',
        role: 'auth',
        about: 'I am a web developer',
    },
    {
        id: 3,
        username: 'abc',
        email: 'ohn@example.com',
        age: 20,
        city: 'New York',
        phone: '123-456-7890',
        password: 'password',
        role: 'auth',
        about: 'I am a web developer',
    },
    {
        id: 4,
        username: 'hrfake',
        email: 'jon@example.com',
        age: 20,
        city: 'New York',
        phone: '123-456-7890',
        password: 'password',
        role: 'auth',
        about: 'I am a web developer',
    },
]
export default users;