var users = [
    {
        id: 1,
        username: 'johnjohn',
        firstname: 'John',
        lastname: 'Danny',
        email: 'john@example.com',
        age: 20,
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        zip: '10001',
        phone: '123-456-7890',
        password: 'password',
        role: 'auth',
        about: 'I am a web developer',
    },
    {
        id: 2,
        username: 'array',
        firstname: 'John',
        lastname: 'Fancy',
        email: 'john@example.com',
        age: 20,
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        zip: '10001',
        phone: '123-456-7890',
        password: 'password',
        role: 'auth',
        about: 'I am a web developer',
    },
    {
        id: 3,
        username: 'abc',
        firstname: 'John',
        lastname: 'David',
        email: 'john@example.com',
        age: 20,
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        zip: '10001',
        phone: '123-456-7890',
        password: 'password',
        role: 'auth',
        about: 'I am a web developer',
    },
    {
        id: 4,
        username: 'hrfake',
        firstname: 'Adam',
        lastname: 'Danny',
        email: 'john@example.com',
        age: 20,
        address: '123 Main St',
        city: 'New York',
        state: 'NY',
        zip: '10001',
        phone: '123-456-7890',
        password: 'password',
        role: 'auth',
        about: 'I am a web developer',
    },
]
export default users;